export const SC_STORE_READY = "SUPERCOLLIDER-REDUX_SC_STORE_READY";
export const SC_STORE_INIT =
  "SUPERCOLLIDER-REDUX_SC_STORE_INIT";
export const SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT =
  "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT";
export const SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED =
  "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED";
