export const SUPERCOLLIDER_READY = "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_READY";
export const SUPERCOLLIDER_INIT_START =
  "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_INIT_START";
export const SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT =
  "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT";
export const SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED =
  "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED";
