"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED = exports.SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT = exports.SUPERCOLLIDER_INIT_START = exports.SUPERCOLLIDER_READY = void 0;
var SUPERCOLLIDER_READY = "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_READY";
exports.SUPERCOLLIDER_READY = SUPERCOLLIDER_READY;
var SUPERCOLLIDER_INIT_START = "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_INIT_START";
exports.SUPERCOLLIDER_INIT_START = SUPERCOLLIDER_INIT_START;
var SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT = "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT";
exports.SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT = SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT;
var SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED = "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED";
exports.SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED = SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED;