export const SC_STORE_INIT: "SUPERCOLLIDER_REDUX-SC_STORE_INIT";
export const SC_STORE_READY: "SUPERCOLLIDER_REDUX-SC_STORE_READY";
export const SC_LANG_INIT: "SUPERCOLLIDER_REDUX-SC_LANG_INIT";
export const SC_LANG_READY: "SUPERCOLLIDER_REDUX-SC_LANG_READY";
export const SC_LANG_QUIT: "SUPERCOLLIDER_REDUX-SC_LANG_QUIT";
export const SC_SYNTH_READY: "SUPERCOLLIDER_REDUX-SC_SYNTH_READY";
