"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DEFAULT_ACTION_LISTENER_PORT = exports.DEFAULT_MOUNT_POINT = exports.READY_STATES = void 0;
const READY_STATES = {
  NOT_STARTED: "NOT_STARTED",
  INIT: "INIT",
  READY: "READY"
};
exports.READY_STATES = READY_STATES;
const DEFAULT_MOUNT_POINT = "SCRedux";
exports.DEFAULT_MOUNT_POINT = DEFAULT_MOUNT_POINT;
const DEFAULT_ACTION_LISTENER_PORT = 3335;
exports.DEFAULT_ACTION_LISTENER_PORT = DEFAULT_ACTION_LISTENER_PORT;